version: '3.8'

services:
  dynamodb-local:
    container_name: dynamodb-local-container
    image: amazon/dynamodb-local:1.16.0
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodb
volumes:
  dynamodb_data:
